### ISSUE TITLE
iOS AirPlay

### ISSUE THREAD

**Issue by KenHowe2010** [adamfisher/Xamarin.Forms.VideoPlayer#102]
Hi,
How do I gain access to Airplay so I can request the video to be displayed on other devices?

Is there a way to gain access to the Native AVPlayer control?

Thanks
-- Ken

**Comment by eopeter** [comment]
Use the CustomRenderer

**Comment by KenHowe2010** [comment]
Thanks for the response, how do I get at the CustomRenderer. I have the VideoPlayer control on a ContentPage. Is there an Example in the project that comes with he control?

**Comment by adamfisher** [comment]
Hello Ken. You will want to check out the Xamarin Forms Custom Renderer documentation. Below is an example snippet of a class you would create in your platform-specific iOS project. Note there might be other methods you would prefer to override instead of `OnElementChanged` depending on what AirPlay integration requires. The `PlayerControl` property will contain the `AVPlayerViewController` instance.

```
public class CustomVideoPlayerRenderer : VideoPlayerRenderer
{
    protected override void OnElementChanged(ElementChangedEventArgs<VideoPlayer> e)
    {
        base.OnElementChanged(e);
        // Do something with PlayerControl property of type AVPlayerViewController
    }
}
```
