### ISSUE TITLE
 iOS - VideoPlayerRenderer.DidPlayToEndTimeNotification

### ISSUE THREAD

**Issue by Nicolas40a** [adamfisher/Xamarin.Forms.VideoPlayer#13]
Hello, 
I have this erreur on iPhone. The player works and displays fine but as soon as the video reaches the end, I have this exception: System.NullReferenceException: Object reference not set to an instance of an object

I created this issue on bitbucket but I'm not sure which one you're using, so sorry for double.

Here is the raw StackTrace :

> at Octane.Xam.VideoPlayer.iOS.Renderers.VideoPlayerRenderer.DidPlayToEndTimeNotification (Foundation.NSNotification obj) [0x0009a] in <f16783ed135143cdbe69ee2202a4080f>:0 
at Foundation.InternalNSNotificationHandler.Post (Foundation.NSNotification s) [0x00000] in /Users/builder/data/lanes/3985/ba11e481/source/xamarin-macios/src/Foundation/NSNotificationCenter.cs:48 
--- End of stack trace from previous location where exception was thrown --- 
at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr) at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3985/ba11e481/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/3985/ba11e481/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
at LeJeuDesProblemes.iOS.Application.Main (System.String[] args) [0x00008] in /Users/benjaminmico/Downloads/LeJeuDesProblemes/LeJeuDesProblemes/LeJeuDesProblemes/LeJeuDesProblemes.iOS/Main.cs:17

**Comment by Nicolas40a** [comment]
Hi,

Any news on this bug?
Can I provide more information to help?
I'm stuck on the development and really would like it to work.

Thanks

**Comment by adamfisher** [comment]
I tried to recreate your issue but it successfully calls my completed method handler when it is finished. Can you please share the code you use to setup the player as well as the URL/source you are attempting to pass it?

**Comment by Nicolas40a** [comment]
Thanks for your help.
Here is the code I'm using to setup the player :

videoView = new VideoPlayer()
            {
                AutoPlay = true,
                DisplayControls = false,
                FillMode = FillMode.ResizeAspect,
                Repeat = false,
                Source = info.VideoPath
            };

The video path is the path of a video I download and locally save on the phone storage that way :

string path = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
var filePath = Path.Combine(path, videoName);
File.WriteAllBytes(filePath, contents));
info.VideoPath = filePath;

The player works fine on Android with the exact same code (just the local folder path is different obviously).
The video is mp4 video and the path folder is very very long on iphone btw.

**Comment by adamfisher** [comment]
Well the fact the video plays tells me it successfully finds the file. So that code seems fine. Can you provide the video file? Even better would be your cleaned and zipped project and I could take a look. You can send it to the outlook email address that issued your license keys.

**Comment by Nicolas40a** [comment]
I will try to provide you a version of my project during the weekend.
I'm still using the trial version with sample videos since the project is still under development.

**Comment by Nicolas40a** [comment]
Hi Adam,

I shared a sample of my projet on bitbucket.
I just added you to the repository Nicolas-Q/ljdp_sample_iphone.

Thank you for your help.

**Comment by adamfisher** [comment]
Thanks Nicolas. I am having problems building your solution. However I have been looking through it. Does the stream always fail for any video source you pass or is it just the URLs you get back from Google's API? In your IDE console window you should see a line starting with "Video Source: " that will show you the URL passed into the player. If you could provide that URL, it would be much appreciated.

On a side note, it looks like you have done a lot of extra work to download the video before passing it to the player. AVPlayer is smart enough to open a remote URL path and begin buffering it for playback. So all you should need to do is pass the URL you get back from Google APIs directly into your player.

**Comment by Nicolas40a** [comment]
Sorry about that, It builds on my side so I thought it would be okay.
I simplified the project even more and pushed that on the repository. I hope this it works.

The stream fail also when I pass a URL yes. I tried with the ocean video link that you use for your demo and it does the exact same think.
On the new sample version, I removed the download and just play the ocean video though just an URL.

Thanks for the advice btw, I will see if I can use this the way I want on my project.

**Comment by adamfisher** [comment]
Unfortunately I am still unable to run your solution due to some error with `Microsoft.Bcl.Build`. This component has been popular and I am surprised you are the first person to experience this. Given I am also able to successfully play to the end and others as well up to this point. Nothing stands out as problematic just reviewing the code.

Here are some things that come to mind you could check or try:

1. Make sure you are not getting a `VideoPlayerLicenseException` anywhere in your IDE debug output as you stated earlier you were running it as a trial. If the playback time is greater than 15 seconds, you would get a message in the console log: "You cannot play a video longer than 15 seconds."
2. Although it shouldn't matter, specify the OnComplete event before you assign a media source.
3. Reset your simulator and clean your solution to make sure there are no cache issues.
4. If you are unable to follow along with the [YouTube tutorial](https://youtu.be/JJ8NuGe_Fr8?t=11m29s) and successfully get a video playing or running the Chill Player example application in this GitHub repo, then that pinpoints the problem to a configuration issue with your system as I have had consistent results from others getting these items to work when their own projects had an issue.
5. If Chill Player works for you, you could work backwards, copying/pasting/deleting the files from your existing project into the ChillPlayer project and renaming it. I have had to do this before. It's not fun but a last resort when things get weird with my csproj configuration for whatever reason.

I hate to say it but sadly if all else fails, you can always contact the component store and request a refund and implement your own video solution. I am running out of ideas :-(

**Comment by Nicolas40a** [comment]
I updated the repository without the Microsoft.Bcl.Build NuGet so at least this should not be a problem anymore...
I am actually using the "Completed" event (if this is the one that you're talking about) but the crash occurs before this event is triggered.

**Comment by adamfisher** [comment]
Yes, the **Completed** is what I am referring to. My best guess is the exception occurs either because the video player is null (could happen if the player isn't being recycled/reused properly when switching between pages) **or** because Apple's notification center doesn't like the media meta data and tries to return a bad NSNotification. I suspect the former. Can you provide a specific URL I can try on my end?

**Comment by Nicolas40a** [comment]
Since I am not using video directly from an URL, I had to find a short random one.
This should work, though it's the one I use in my sample so it should be using it already.
https://img-9gag-fun.9cache.com/photo/axV3YyY_460sv.mp4

**Comment by Nicolas40a** [comment]
Hi Adam,
Were you able to reproduce the error on my project?

**Comment by adamfisher** [comment]
I tested it out and the video completes successfully and fires the `Completed` event successfully. I'm sorry I can't be of more help in this instance @Nicolas40a. I would recommend my original suggestion above and try to work backwards from the Chill Player example application that comes packaged with the component, dragging and dropping your files into that project as that approach has consistently worked for the small few people who have had issues with their local builds (solutions # 5). It's a last resort of course but has worked well in the past.

**Comment by guidebee** [comment]
looks like mine is same issue here.
https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/issues/21
