### ISSUE TITLE
Doesn't run in release mode

### ISSUE THREAD

**Issue by dhuynhtek** [adamfisher/Xamarin.Forms.VideoPlayer#137]
Video player doesn't seem to work in release mode. Everything works fine in debug mode. I thought this was a bug in our code but when I tried to run the sample app (ChillPlayer) in release mode it kept crashing with the System.PlatformNotSupportedException. 

Any ideas on how to fix this?

Thanks

![capture](https://user-images.githubusercontent.com/41075091/44605866-00435080-a7b9-11e8-98a8-514d8c6cad83.JPG)

**Comment by nitrouscutter** [comment]
Any update on this? We have to use debug mode to show our videos in our app because the release mode version from the store wont play in UWP.

**Comment by nitrouscutter** [comment]
@adamfisher I found that running UWP with flag "Compile with .NET Native tool chain" for release mode makes the player not work. Having this unchecked the player will work fine. Usually we want this flag checked for UWP release in order to improve performance. The question now is, why does the player not with with native?

**Comment by nitrouscutter** [comment]
@adamfisher I narrowed it down to needing to add the library or assembly with namespace and child elements to the Default.rd.xml file located int he properties folder in the UWP project. Cant figure out the correct format to that, but once thats right it should run with that flag on.
