### ISSUE TITLE
Loading new Source to the same VideoPlayer instance - the film starts with wrong frame

### ISSUE THREAD

**Issue by ghost** [adamfisher/Xamarin.Forms.VideoPlayer#143]
Hello,
I use commercial version of VideoPlayer and my customer found out such bug.
1. I create the instance of VideoPlayer
2. I set the Source and load the video file
3. I set Source to null
4. I set another film to the Source
5. The film starts form the last frame of the previous film - what makes my customer furious :)

The bug is identified for:
1. Android 6,7,8
2. Octane.Xam.VideoPlayer ver 2.2.0

The process is shown in my screencapture below:
http://77.253.224.93:8080/share.cgi?ssid=0wZGRIh

**Comment by adamfisher** [comment]
This component simply wraps the native/default video player already packaged on each platform (iOS - AVPlayerViewController, Android - MediaPlayer, UWP - MediaElement) so that would be the same behavior if you were to pass in that same series of source file parameters. To fix it, it might be best to dispose of the current player you are using and use a new instance.
