### ISSUE TITLE
Ablility to display thumbnail?

### ISSUE THREAD

**Issue by attrib75** [adamfisher/Xamarin.Forms.VideoPlayer#161]
Hi, this is just a question.  Can the first frame or thumbnail be displayed initially without auto play set to true?

I tried 
   player.Seek(1);
   player.Play();
    player.Pause();

on an h264 video with progressive playback format.  I thought this might get the first frame to load and pause, but it did not.  Any help would be appreciated.  thanks

**Comment by attrib75** [comment]
The problem probably is that I'm trying to display these in a listview, with some sort of thumbnail or indicator that the item is a video.  I've set display controls to true, but they do not appear

**Comment by adamfisher** [comment]
I would avoid assigning a source to the player until you are ready to actually play it because that will consume system resources if the autoplay is set to true. You may need to use some other native API to capture screenshots from the video to display thumbnails. I'm not familiar with any immediately that would help with that but I would just swap the thumbnail out for a single instance of the player when a user taps on a thumbnail.

**Comment by wesoos** [comment]
Hi was there any solution to this?  I would like to grab a snapshot of the video playing?
