### ISSUE TITLE
Two continues Videos not showing properly.

### ISSUE THREAD

**Issue by sharatchandra99** [adamfisher/Xamarin.Forms.VideoPlayer#22]
Hi,

We are planing to buy this video player plugin and we tried sample version. its working fine in a single page. But once I created second page and am sending the first page player related source path to second page.Then, the first page player overlaps the second page player.  

Can you please look into this.

Thanks in advance.

**Comment by guidebee** [comment]
I actually had exactly same issue. when have video players on two pages, the video sometimes overlapping, even the page behind is suppose to be invisible.   I guess this issue probably not related to the video player itself, instead the problem could lie in the Xamarin itself.  

The issue happens when switch to second page while on the first page is video hasn't start playing yet (async behaviour ) 
after the second page shown ,both player start playing . two videos overlapping.

I had a workaround, listen to the video player's Playing event,  and then check player is not the top page or not,if not ,cancel the playing ,something like this

```chsarp
VideoPlayer.Playing += VideoPlayer_Playing;

private void VideoPlayer_Playing(object sender, VideoPlayerEventArgs e)
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                //Fix Xamarin bugs. Workaround
                if ((ContainerPage != SessionInfo.CurrentPage))
                {
                    VideoPlayer.Source = "";
                    VideoPlayer.IsVisible = false;
                }
            });
        }
```

Hope this helps. this issue could be the player issue also.

**Comment by adamfisher** [comment]
You are correct it is partially to do with Xamarin Forms but more specifically Android. The `VideoView` uses a `SurfaceView` to render the graphics and it does not respect the Xamarin Forms view hierarchy.

You need to set the `IsVisible` property to false and potentially stop the player in the `OnDisappear()` method of the page before navigating to the next page. It has to do with how the surface pokes a hole in the view hierarchy causing it to no respect the traditional Xamarin Forms view hierarchy. 

The Chill Player example app in this repo also shows this example when navigating from the main menu to another page.
