### ISSUE TITLE
Exoplayer lib?

### ISSUE THREAD

**Issue by fmeneuhe** [adamfisher/Xamarin.Forms.VideoPlayer#29]
Hi,
Has this plugin the possibility to use the Google Exoplayer lib for Android in order to reproduce a wider streaming video formats?
Thanks

**Comment by adamfisher** [comment]
It is certainly possible but would require re-implementing the properties and events you want to expose from ExoPlayer. Since it is a non-default player however, you would probably want to pull in the [ExoPlayer nuget package](https://www.nuget.org/packages/Xam.Plugins.Android.ExoPlayer/) and then create a Xamarin Forms custom renderer in your native Android project with a declaration like this for the `VideoPlayerRenderer` class you create:

`[assembly: ExportRenderer(typeof(VideoPlayer), typeof(VideoPlayerRenderer))]`
