### ISSUE TITLE
Setting VideoSource to null does not stop the current video.

### ISSUE THREAD

**Issue by Levent0z** [adamfisher/Xamarin.Forms.VideoPlayer#51]
VideoPlayer is set to AutoPlay.  VideoSource is two-way bound. Changing it to a different value makes the video change. However, setting it to null does not stop the currently playing video. This is on Android,

**Comment by JKennedy24** [comment]
I think this error means the Video player is not being disposed of correctly.

Which means if you then reset the video source to something else you get this error:

`Android.Views.WindowManagerBadTokenException: Unable to add window -- token null is not valid; is your activity running?
`

**Comment by JKennedy24** [comment]
This also happens on ios. Very reluctant to buy this component if even the simple things such as this don't work

**Comment by adamfisher** [comment]
A while ago there was an issue related to errors occurring in one or more of the native video players if setting the source to `null` was permitted which is why we guard against it to prevent the error from occurring. So if the path is `null`, empty, or malformed, we will not update the native player's source to replace whatever is currently in it since this behavior is not consistent across all platforms. As with any cross-platform component like this, the lowest common denominator of behavior/features are usually what drive product decisions.

If you still wish to have the native player force the value to be null when it is set in the Xamarin Forms control, you can implement a Xamarin Forms Custom Renderer in your Android project and override the behavior as desired:

```csharp
public class MyVideoPlayerRenderer : VideoPlayerRenderer
{
   public MyVideoPlayerRenderer(Context context) : base(context)
   {
   }

   protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
   {
      if (e.PropertyName == VideoPlayer.SourceProperty.PropertyName && Element?.Source == null)
      {
         // Only set to null when the source of the player is set to null
         Control.SetVideoPath(null);
      }
      else
      {
         // Do the normal behavior and update the player accordingly
         base.OnElementPropertyChanged(sender, e);
      }
   }
}
```
