### ISSUE TITLE
Full Screen option on Android devices

### ISSUE THREAD

**Issue by albertoiglesias2001** [adamfisher/Xamarin.Forms.VideoPlayer#53]
Hello Adam, 

We are using your component and it works very well, it works in both portrait and landscape. The problem is that the "Full Screen" option does not appear on Android devices, it only appears on iOS.

I made an application in native code for Android and it works, that is, it is not limited to Android and yes the component

Can you check this problem?

Check the option in my native app:

![fullscreen](https://user-images.githubusercontent.com/18347714/28614129-98e57704-71ec-11e7-97a4-f321838337e3.jpg)

**Comment by adamfisher** [comment]
Glad to hear you are getting some use out of the component 👍 

The goal of this component is to render the native video player of each platform. So on Android we use the `VideoView` and iOS uses the `AVPlayer`. So it really comes down to what each individual platform's default experience provides and as such, it is not something we could expose as a full screen XAML property since not all platforms support it out of the box.

If you want to get more fine-grained control of the component, you can extend the `VideoPlayerRenderer` in your iOS or Android project and access the `Control` property in your own custom renderer to access native methods and fields of the underlying video player. I know Android specifically offers a `MediaController` property that would allow you to replace the default one Android creates with your own controls. You may find [some tutorials online](https://stackoverflow.com/questions/34919058/how-to-make-videoview-full-screen) helpful in adding this advanced functionality to the player.
