### ISSUE TITLE
Minimum supported version on Android

### ISSUE THREAD

**Issue by Levent0z** [adamfisher/Xamarin.Forms.VideoPlayer#55]
One of my testers reported that none of the videos work on his Android tablet version 4.1.2.

According to the VideoPlayer component site, the minimum version supported is 4.1+. API Level 16? Is this accurate? I've built the Android binary with a level of 15, does that matter?

**Comment by adamfisher** [comment]
The Android version makes use of the `VideoView` and in order to support all of the different options you have in the documentation there were some requirements that caused issues around earlier API levels. If you are looking to support that far back, you may need to extend the video player's `VideoPlayerRenderer` in your Android project and conditionally override any method that gives you grief with earlier versions. Alternatively, you could just target a later API version since [only 2.8% of the world is using level 16 currently](https://developer.android.com/about/dashboards/index.html).
