### ISSUE TITLE
Android fails to load video with https

### ISSUE THREAD

**Issue by pdougla002** [adamfisher/Xamarin.Forms.VideoPlayer#59]
Hi Adam,
The mp4 I'm using is from an azure server, and works fine in iOS. It will not play on Android.
As a test, I moved the mp4 to a site using http and it loaded and played fine on Android. 
This is the only blocker for me - unfortunately all my video files are going to be served via https. I am attaching the output from Visual Studio.
[VideoPlayer_output_Android.txt](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/files/1244014/VideoPlayer_output_Android.txt)

Thank you!
PD

**Comment by pdougla002** [comment]
Hi @adamfisher have you had a chance to look at this? If you need an https URL I can provide some,
Thanks,
Pete

**Comment by adamfisher** [comment]
As you can see from the partial stack trace below, the issue occurs with the native Android `MediaPlayer` unable to find a content provider capable of handling HTTPs. 

> **Note:** HTTPS is not supported before Android 3.1.

```
08-03 21:39:11.978 I/SurfaceView(20285): surfaceCreated callback +, this = Octane.Xam.VideoPlayer.Android.Widget.VideoView\{2555a91 VFE...... .F....ID 0,0-720,1136\}\
08-03 21:39:11.982 E/MediaPlayer(20285): setDataSource: IOException! uri=https://defaultwebcentralus224.blob.core.windows.net/wowvideos/636373709759305171hb.mp4\
08-03 21:39:11.982 E/MediaPlayer(20285): java.io.FileNotFoundException: No content provider: https://defaultwebcentralus224.blob.core.windows.net/wowvideos/636373709759305171hb.mp4\
08-03 21:39:11.982 E/MediaPlayer(20285): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1123)\
08-03 21:39:11.982 E/MediaPlayer(20285): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:958)\
08-03 21:39:11.982 E/MediaPlayer(20285): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:881)\
08-03 21:39:11.982 E/MediaPlayer(20285): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1018)\
08-03 21:39:11.982 E/MediaPlayer(20285): 	at android.widget.VideoView.openVideo(VideoView.java:437)\
```

Some things to try:

- Pass the URL without the protocol: `//:example.com/video.mp4`
- Instead of using XAML, make an explicit call to `myPlayer.Source = VideoSource.FromUri("");` trying it with/without the protocol.
- Finally it may come to [creating an Android content provider](https://developer.android.com/guide/topics/providers/content-provider-creating.html) to extend the `ContentProvider` class and register it in your AndroidManifest.xml. Unless you have altered the manifest, I'm surprised you would need to do this as Android projects don't have an issue with this by default as is the case with the Chill Player example app I was able to verify it does work with the azure URL you mentioned above.

**Comment by pdougla002** [comment]
Thanks Adam, I appreciate your advice. I'll give these ideas a try.
Pd

**Comment by pdougla002** [comment]
The URL below does not work in my app or the Chill Player (Android) either. I tried your suggestions regarding the protocol, no dice. I can play this URL in a Xamarin WebView. Not sure where to go with this :@/
"https://defaultwebcentralus224.blob.core.windows.net/wowvideos/636373709759305171hb.mp4"

**Comment by adamfisher** [comment]
I am showing that URL as broken. I do remember testing this a while back successfully on the Chill Player example application. HTTPs streams have worked for many other users. One thing that is sometimes helpful is to start with Chill Player's manifest and configuration files and then work to get your project specific items inserted from there. Specifically the AndroidManifest.xml is of particular interest since that is where the content provider configuration lives.

**Comment by pdougla002** [comment]
Thanks Adam,
Yes the urls are periodically regenerated. They are usually good for a
couple weeks. Do you have an https URL that I can compare. Maybe work at it
from both sides, with Chill Player to compare as well.
Pd

**Comment by pdougla002** [comment]
I've been flailing on this for some time. This has me beat. It is not a problem with the Octane player. I can't even get it to play in a simple java Android project using MediaPlayer or VideoView approaches. It does complain about the **(java.io.FileNotFoundException: No content provider)** 
Here is a newer sample video ( I can download the video and play it as a local resource but that's not the ticket) :
https://defaultwebcentralus224.blob.core.windows.net/wowvideos/636403108616662155hb.mp4

**Comment by pdougla002** [comment]
We are retrieving our videos from another source now (Azure Media Server) with no problems. This can be closed. Thanks for your help.

**Comment by voidsstr** [comment]
Looked into this for a while - the exception 'java.io.FileNotFoundException: No content provider' is always logged in the device console even if the video plays successfully. I think the issue I was running into was an issue more related to how the video player is nested within other views within my xaml file.
