### ISSUE TITLE
Ducking background audio

### ISSUE THREAD

**Issue by mikehamsa** [adamfisher/Xamarin.Forms.VideoPlayer#65]
Hello,

More of a question at this point while I evaluate different cross platform video players. On android is it possible to have your Video Player request audio focus as AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK? I'd like to allow the user to play background music (with an app like Google Play Music) while my app is using the video player to play a video and have the two audio streams play together.

I hope that makes sense.

Many Thanks,
Mike...

**Comment by adamfisher** [comment]
The `VideoView` is used as the underlying implementation for the Android platform and I see the default value for it is set to `AudioManager.AUDIOFOCUS_GAIN`.

https://developer.android.com/reference/android/widget/VideoView.html#setAudioFocusRequest(int)

In order to change that value, you would need to create a [Xamarin Forms custom renderer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/) that extends `VideoPlayerRenderer` in your Android project. Something like this:

```
public class MyVideoPlayerRenderer : VideoPlayerRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<VideoPlayer> e)
        {
            base.OnElementChanged(e);
            Control.AudioFocus = AudioFocus.GainTransientMayDuck;
        }
    }
```

Here is the official documentation from the source code for it:
```
/**
--
  | * Sets which type of audio focus will be requested during the playback, or configures playback
  | * to not request audio focus. Valid values for focus requests are
  | * {@link AudioManager#AUDIOFOCUS_GAIN}, {@link AudioManager#AUDIOFOCUS_GAIN_TRANSIENT},
  | * {@link AudioManager#AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK}, and
  | * {@link AudioManager#AUDIOFOCUS_GAIN_TRANSIENT_EXCLUSIVE}. Or use
  | * {@link AudioManager#AUDIOFOCUS_NONE} to express that audio focus should not be
  | * requested when playback starts. You can for instance use this when playing a silent animation
  | * through this class, and you don't want to affect other audio applications playing in the
  | * background.
  | * @param focusGain the type of audio focus gain that will be requested, or
  | *    {@link AudioManager#AUDIOFOCUS_NONE} to disable the use audio focus during playback.
  | */
  | public void setAudioFocusRequest(int focusGain);
```
