### ISSUE TITLE
PushAsync on iOS fullscreen causes unwanted behaviour when calling Completed callback.

### ISSUE THREAD

**Issue by leoalvaleo** [adamfisher/Xamarin.Forms.VideoPlayer#66]
Hi there!

When I try to go to another navigation page when video finishes is in Fullscreen on iOS makes the video player unable to go back to the page.

How can I know if the user entered and exited fullscreen on iOS?
Thanks

**Comment by adamfisher** [comment]
A full screen option is not exposed on the player by default since not all platforms have a full screen button on their video player.  You can use KVO to observe the `videoBounds` property of the `AVPlayerViewController` instance which is what is used for the native platform implementation by possibly using a [Xamarin Forms Effect](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/effects/touch-tracking/) or a [Xamarin Forms Custom Renderer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/).

If you decide to go the custom renderer route, you can check out this Stack Overflow post on some of the native APIs you would need to manipulate on the bounds of the player when you extend `VideoPlayerRenderer` in your iOS-specific project.

https://stackoverflow.com/questions/26330287/how-to-detect-fullscreen-mode-of-avplayerviewcontroller
