### ISSUE TITLE
No Fullscreen nor volume controls on Android?

### ISSUE THREAD

**Issue by taublast** [adamfisher/Xamarin.Forms.VideoPlayer#78]
When using DisplayControls="True" logically might be using native controls, and i have no Fullscreen nor volume controls, tested onAndroid?..

**Comment by adamfisher** [comment]
`DisplayControls="True"` toggles the showing the `MediaController` play/pause/stop/etc. in the case of Android. The controls will vary by platform because it is the native controls the platform offers. Of course you also have the option of setting `DisplayControls="False"` and adding your own to the screen as shown in the VideoPlayerQueuePage.xaml example of the Chill Player application. All of the properties on the player are bindable.

There is also a `Volume` property on the player itself and modifying it will change it from using whatever the default system value was (the default behavior).
