### ISSUE TITLE
Tap Gesture While Playing

### ISSUE THREAD

**Issue by eopeter** [adamfisher/Xamarin.Forms.VideoPlayer#89]
How do I attach to the tap gesture while playing? I tried the following but it did not trigger:

`<o:VideoPlayer.GestureRecognizers>
                       <TapGestureRecognizer Tapped="videoTapped_Tapped" />
                    </o:VideoPlayer.GestureRecognizers>`

Thanks a lot!!!

**Comment by adamfisher** [comment]
Tap gestures are not currently implemented with the player since the view used by the native platform to render the media does not respect the view hierarchy of Xamarin Forms. This is especially true on Android where Android's `MediaPlayer` makes use of a heavy `SurfaceView` to render the media. It is sort of like poking a hole in the view hierarchy.

You might give the following tutorial a try by extending the `VideoPlayerRenderer` and implementing the necessary callbacks to capture touch events.

http://arteksoftware.com/gesture-recognizers-with-xamarin-forms

**Comment by adamfisher** [comment]
I am going to mark this as an enhancement. I may try to include this into the component in a future release.

**Comment by mmsteve** [comment]
This is actually quite detrimental to my use case of the player as there is no "native back button" on iOS and therefore no way to unobtrusively add a back button to the player without just taking up part of the screen (which is obviously a terrible idea for media streaming applications).

A solution was to add a TapGestureRecognizer to the video player or parent grid and show an overlay which allows the user to use "back" functionality when the element receives any tap inputs. However, this is impossible because neither the parent grid of the video player element itself receives tap gesture inputs.

**Comment by eopeter** [comment]
I was able to put an overlay over the player and hook in the tap gesture.

**Comment by jeffgrau** [comment]
Tap gesture with overlay is working fine for me in UWP. I'm using ExoPlayer for Android and I don't have a Mac yet to test this on iOS.

**Comment by andersonvieiragomeslopes** [comment]
@eopeter Could you share your code?
