### ISSUE TITLE
Crash UWP in Release Mode

### ISSUE THREAD

**Issue by Crem78** [adamfisher/Xamarin.Forms.VideoPlayer#9]
Hi Adam, how to correctly register the plugin in UWP? In debug mode function but in release I get this error:

_Unhandled exception at 0x7704DF95 (combase.dll) in EliorPerTe.UWP.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x06D114B0, 0x00000002)._

I try to register it so in the App.xaml.cs file
```

var assembliesToInclude = new List<Assembly>()
{
	typeof(FormsVideoPlayer).GetTypeInfo().Assembly
};

Xamarin.Forms.Forms.Init(e, assembliesToInclude);
FormsVideoPlayer.Init("MY_KEY");
```

**Comment by adamfisher** [comment]
Mmmh this smells like nuget hell. This could be due to some dependency/package install flakiness around nuget package installs. Might be best to try to completely remove/install the package via nuget.org and make sure you have no dependency warnings. Most the time this is a linker error on Android and iOS but UWP doesn't have that concept.

If there was an internal error with the player you would have gotten a more detailed stack trace.

This appears to be very similar to this thread:
https://forums.xamarin.com/discussion/57179/uwp-immediate-crash-in-release-mode

**Comment by Crem78** [comment]
Hi adam, here's what I did

- Remove and install from Package Manager Console [http://www.nuget.org/packages/Octane.Xam.VideoPlayer/](url)

- I use Microsoft Visual Studio Professional 2015 Version 14.0.25425.01 Update 3

- My Microsoft.NETCore.UniversalWindowsPlatform  is 5.2.2 
Not possible update to 5.3.1 because i don't use VS 2017

- I compile in release mode (ARM) because I see it on my physical device

- I called as per example the assemblies

Unfortunately it does not work

**Comment by adamfisher** [comment]
Unfortunately according to that thread I referenced, this appears to be an issue with Xamarin Forms. 

A similar issue was already opened for this with a potential workaround here:
https://bitbucket.org/OctaneSoftware/octane.xam.videoplayer/issues/28/videoplayer-is-not-able-to-play-videos-on
