### ISSUE TITLE
How to play a local .mov?

### ISSUE THREAD

**Issue by xBoneso** [adamfisher/Xamarin.Forms.VideoPlayer#95]
Hello, I really like this player but is it possible to player a local .mov file?

**Comment by adamfisher** [comment]
Assuming the platforms you are targeting support .mov codec types (this component uses the AVPlayer on iOS, the MediaPlayer on Android, and the MediaElement on Windows Phone), you should be able to include the file as an embedded resource and play it as shown in [`MainMenuPage.xaml`](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/ChillPlayer/ChillPlayer/Pages/MainMenuPage.xaml). It is making use of a markup extension to let the player know it is an embedded resource but you could also just pass it like this in the code-behind:

`myPlayer.Source = VideoSource.FromResource("file.mov");`

**Comment by xBoneso** [comment]
Hello, Thanks! It works! But If I don't want to use an EmbeddedResource (get the video from a local path) how would I do it?

**Comment by adamfisher** [comment]
The Source property takes a `VideoSource` which behaves very similarly to the Xamarin Forms [`ImageSource`](https://developer.xamarin.com/guides/xamarin-forms/user-interface/images/). The same behavior and logic described in that documentation can also be applied here by using VideoSource instead of ImageSource.

If you using remote HTTP URLs just pass them in directly to the **Source** property.
