### ISSUE TITLE
Player in ListView. On Scroll player disappears but still playing

### ISSUE THREAD

**Issue by eopeter** [adamfisher/Xamarin.Forms.VideoPlayer#96]
I am seeing this on iOS where I have the player as first element in ListView. When I scroll up and the player scrolls out of sight, on scrolling back down, the player does not show again but can hear the sound.

**Comment by adamfisher** [comment]
You might have a look at the [`VideoPlayerQueuePage.xaml`](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/ChillPlayer/ChillPlayer/Pages/VideoPlayerQueuePage.xaml) which uses a `StackLayout` to organize the player and a playlist below it.

The `ListView` is likely recycling the cell which is not ideal since the player is a heavy-weight object. I would place it outside of the list and listen for a cell to be tapped and update the player accordingly. Also on a side note, only one player per page is recommended especially with Android since the emulator has known performance issues when you attempt to place multiple players on the screen but your mileage may vary.
